name: NexAuth
main: su.nexmedia.auth.NexAuth
version: '${project.version}'
description: Lightweight and modern authorization system.
author: NightExpress
depend: [NexEngine]
api-version: 1.17

libraries:
  - org.apache.logging.log4j:log4j-core:2.23.0